#!/bin/bash
#
# description: alfr3d init script
#
### BEGIN INIT INFO
# Provides:          alfr3d
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: alfr3d daemon
# Description:       alfr3d daemon
# Start the service alfr3d
### END INIT INFO

RUNAS=root
INITSAY="all alfred services have been initialized"
ENDSAY="Stopping all alfred services"
HOMEDIR=/home/alfr3d/Alfr3d-MKIV

BOTTLEPIDNAME=alfr3dBottle
BOTTLEPIDFILE=/var/run/$BOTTLEPIDNAME

start() {
    echo "Starting alfr3d services: "
    ### Create the lock file ###
    touch /var/lock/alfr3d
    echo

    ### Start the daemon ###
    echo "Starting alfr3d daemon"
    python $HOMEDIR/daemon/alfr3ddaemon.py start > $HOMEDIR/log/init.log &

    ### Initialize resftul interface ###
    if [ -f /var/run/$BOTTLEPIDNAME ] && kill -0 $(cat /var/run/$BOTTLEPIDNAME);
    then
    echo 'Restful interface already running' >&2
    else
    echo "Initializing restful interface" >&2
    local CMD="python $HOMEDIR/run/alfr3dBottle.py > $HOMEDIR/log/init.log & echo \$!"
    su -c "$CMD" $RUNAS > "$BOTTLEPIDFILE"
    echo "Restful interface started" >&2
    fi

    echo "Speaking init greeting"
    pico2wave -w "$HOMEDIR/soundbites/init.wav" "$INITSAY"
    mplayer -ao alsa:device=default -really-quiet -noconsolecontrols "$HOMEDIR/soundbites/init.wav"
}
# Restart the service alfr3d
stop() {
    echo "Stopping alfr3d services: "
    
    echo "Speaking end greeting"
    pico2wave -w "$HOMEDIR/soundbites/end.wav" "$ENDSAY"
    mplayer -ao alsa:device=default -really-quiet -noconsolecontrols "$HOMEDIR/soundbites/end.wav"    

    ### Stop the daemon ###
    echo "Starting alfr3d daemon"
    python $HOMEDIR/daemon/alfr3ddaemon.py stop > $HOMEDIR/log/init.log &
    
    # stop python bottle server
    if [ ! -f "$BOTTLEPIDFILE" ] || ! kill -0 $(cat "$BOTTLEPIDFILE");
    then
    echo "Restful interface is not running" >&2
    else
    echo "Stopping restful interface..." >&2
    kill -15 $(cat "$BOTTLEPIDFILE") && rm -f "$BOTTLEPIDFILE"
    echo "Restful interface stopped"
    fi

    ### Now, delete the lock file ###
    rm /var/lock/alfr3d
    echo
}
status() {
    echo "Checking Alfr3d services"
    if [ -z "`ps axf | grep alfr3ddaemon.py | grep -v grep`" ];
    then
       echo "Alfr3d Daemon is dead"
    else
       echo "Alfr3d Daemon is running"
    fi
    if [ -z "`ps axf | grep alfr3dBottle.py | grep -v grep`" ];
    then
       echo "Alfr3d Restful Interface is dead"
    else
       echo "Alfr3d Restful Interface is running"
    fi
}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status alfr3d
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
exit 0

